import {
  Box,
  Container,
  Text,
  Stack,
  Paper,
  Image,
  Title,
  Anchor,
  List,
} from "@mantine/core";
import logo from "../assets/cot.png";
import { ExternalLink } from "lucide-react";

export function IntroductionSection() {
  return (
    <Box
      component="section"
      py={100}
      style={{
        borderBottom: "1px solid #373a40",
        background: "linear-gradient(180deg, #1a1b1e 0%, #141517 100%)",
      }}
    >
      <Container size="md">
        <Stack gap="xl" align="center">
          <Stack gap="xl" align="center" mb={"lg"}>
            <Image
              src={logo}
              alt="CoT Logo"
              style={{ width: 100, height: 100 }}
            />

            {/* Main Title */}
            <Title order={1} size={38} ta="center">
              Causal Sufficiency and Necessity Improves Chain-of-Thought
              Reasoning
            </Title>
            <Text size="sm" c="dimmed" ta="center">
              explained by{" "}
              <a
                href="https://www.linkedin.com/in/0xahmedkhan"
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  color: "inherit",
                  textDecoration: "underline",
                  textDecorationStyle: "dotted",
                  transition: "color 0.2s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.color = "#228be6")}
                onMouseLeave={(e) => (e.currentTarget.style.color = "inherit")}
              >
                Ahmed Khan
              </a>
              ,{" "}
              <a
                href=""
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  color: "inherit",
                  textDecoration: "underline",
                  textDecorationStyle: "dotted",
                  transition: "color 0.2s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.color = "#228be6")}
                onMouseLeave={(e) => (e.currentTarget.style.color = "inherit")}
              >
                Ayesha Tahir
              </a>{" "}
              &{" "}
              <a
                href=""
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  color: "inherit",
                  textDecoration: "underline",
                  textDecorationStyle: "dotted",
                  transition: "color 0.2s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.color = "#228be6")}
                onMouseLeave={(e) => (e.currentTarget.style.color = "inherit")}
              >
                Marium Zahid
              </a>
            </Text>
          </Stack>

          {/* Introduction Text */}
          <Paper
            p="xl"
            radius="lg"
            style={{
              backgroundColor: "#1a1b1e",
              border: "1px solid #373a40",
              maxWidth: 700,
            }}
          >
            <Stack gap="lg">
              <Text c="dimmed" size="md" style={{ lineHeight: 1.8 }}>
                This interactive explainer distills the core idea from the
                research on{" "}
                <strong>
                  Causal Sufficiency and Necessity in CoT Reasoning
                </strong>
                : not every token in a chain-of-thought is equally important for
                arriving at the right answer.
              </Text>

              <Text c="dimmed" size="md" style={{ lineHeight: 1.8 }}>
                The paper asks two causal questions. First,{" "}
                <strong>necessity</strong>: if we remove a part of the
                reasoning, does performance break? Second,
                <strong> sufficiency</strong>: if we keep only a selected part,
                does it still preserve performance? These two lenses reveal
                which reasoning components truly matter.
              </Text>

              <List spacing="xs" size="sm" c="dimmed" withPadding>
                <List.Item>
                  <strong>Chain-of-thought (CoT):</strong> the step-by-step
                  rationale generated by a model.
                </List.Item>
                <List.Item>
                  <strong>Necessary information:</strong> pieces that cannot be
                  removed without harming the final answer.
                </List.Item>
                <List.Item>
                  <strong>Sufficient information:</strong> the minimal pieces
                  that are enough to retain correct reasoning.
                </List.Item>
              </List>

              <Text c="dimmed" size="md" style={{ lineHeight: 1.8 }}>
                We use a narrative progression in this living paper: build
                intuition first, then move into a concrete analysis of necessity
                and sufficiency in Section 1.
              </Text>

              <Text size="sm" c="dimmed" ta="center">
                Original paper:{" "}
                <Anchor
                  href="https://arxiv.org/pdf/2506.09853"
                  target="_blank"
                  rel="noopener noreferrer"
                  underline="hover"
                >
                  Causal Sufficiency and Necessity Improves Chain-of-Thought
                  Reasoning
                  <ExternalLink size={12} style={{ marginLeft: 5 }} />
                </Anchor>
              </Text>

              <Text size="sm" c="dimmed" ta="center" fs="italic">
                Scroll down to begin.
              </Text>
            </Stack>
          </Paper>
        </Stack>
      </Container>
    </Box>
  );
}
